SHOW DATABASES;
CREATE DATABASE test;
SHOW DATABASES;
USE test;
DROP DATABASE test;
USE opc_cources;
CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30),
  age INT);
DESC users;

INSERT INTO users VALUES (NULL , 'IVAN', 26);
SELECT * FROM users;
INSERT INTO users VALUES (NULL , 'PETR', 28);
